version: '3'

services:
  db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db

  app:
    build:
      context: .
      dockerfile: base_hw29.docker

    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: test_db
      DB_USER: user
      DB_PASSWORD: pass
